node:
  data_dirs:
  - data
  template_dirs:
  - templates
  output_dir: node
  overlay_files: []
  feed_dir: feeds
  dist_map: dist_map.json
  dist_json: distributions.json
  catalogue_file: catseye.catalogue
  checkout_dir: checkout
  projection_dir: modules
  link_priority_files:
  - retrocomputing-refdex.json
  - misc-refdex.json

installation:
  data_dirs:
  - data/installation
  template_dirs:
  - templates
  output_dir: installation
  overlay_files: []
  feed_dir: feeds
  dist_map: dist_map.json
  dist_json: distributions.json
  checkout_dir: checkout
  projection_dir: modules
  link_priority_files:
  - retrocomputing-refdex.json
  - misc-refdex.json
