node:
  data_dirs:
  - data
  template_dirs:
  - templates
  output_dir: node
  overlay_files: []
  feed_dir: feeds
  dist_map: dist_map.json
  catalogue_file: catseye.catalogue
  checkout_dir: checkout
  projection_dir: modules
  link_priority:
    Jeffry Johnston: http://esolangs.org/wiki/Jeffry%20Johnston
    Phantom Hoover: http://esolangs.org/wiki/User:Phantom_Hoover
    Paul Harrison: http://www.logarithmic.net/pfh/
    zzo38: http://esolangs.org/wiki/User:zzo38
    Fabrice Bellard: https://bellard.org/
    Rube Goldberg: https://en.wikipedia.org/wiki/Rube_Goldberg
    Milo van Handel: http://esolangs.org/w/index.php?search=Milo+van+Handel&title=Special%3ASearch&go=Go
    Lawrence Landweber: http://www.worldcat.org/identities/lccn-n88653901/
    Walter Brainerd: http://worldcat.org/identities/lccn-n82105386/
    Anonymous: https://en.wikipedia.org/wiki/Anonymous_work
    David Chipping: http://esolangs.org/w/index.php?search=David+Chipping&title=Special%3ASearch&go=Go
    Stephen Bourne: https://en.wikipedia.org/wiki/Stephen_R._Bourne
    Brian Connors: http://esolangs.org/w/index.php?search=Brian+Connors&title=Special%3ASearch&go=Go
    Frédéric van der Plancke: http://esolangs.org/wiki/Fr%C3%A9d%C3%A9ric_van_der_Plancke
    Catatonic Porpoise: http://esolangs.org/wiki/Scott_Feeney
    ais523: http://esolangs.org/wiki/User:ais523
    Niels Serup: http://esolangs.org/wiki/User:Nqpz
    Andrew Turley: http://esolangs.org/w/index.php?search=andrew+turley&title=Special%3ASearch&go=Go
    Tslil Clingman: http://esolangs.org/wiki/Tslil_Clingman
    Gregory Yob: https://en.wikipedia.org/wiki/Gregory_Yob
    Urban Müller: http://esolangs.org/wiki/Urban_M%C3%BCller
    Francis Rogers: http://esolangs.org/w/index.php?search=Francis+Rogers&title=Special%3ASearch&go=Go
    Marinus: http://esolangs.org/wiki/User:Marinus
    Merman Helville: http://catseye.tc/installation/Doby_Mick
    Fabian Hemmer: https://github.com/copy
    Michael C. Martin: https://github.com/MichaelCMartin
    Konrad Zuse: https://en.wikipedia.org/wiki/Konrad_Zuse
    John S. James: https://www.atariarchives.org/morebasicgames/showpage.php?page=61
    Frank Zappa: https://en.wikipedia.org/wiki/Frank_Zappa
    Daniel Brockman: http://esolangs.org/wiki/Daniel_Brockman
    Steven Goodwin: https://web.archive.org/web/20130817001802/http://www.bluedust.dontexist.com:80/spoon/
    Ryan Kusnery: http://esolangs.org/wiki/Ryan_Kusnery
    Boily: http://esolangs.org/wiki/User:boily
    Cliff L. Biffle: http://esolangs.org/wiki/Cliff_L._Biffle
    Wouter van Oortmerssen: http://strlen.com/
    Don Woods: https://en.wikipedia.org/wiki/INTERCAL
    James M. Lyon: https://en.wikipedia.org/wiki/INTERCAL
    Matthew Westcott: http://esolangs.org/w/index.php?search=Matthew+Westcott&title=Special%3ASearch&go=Go
    John Conway: https://en.wikipedia.org/wiki/John_Horton_Conway
    Schrödinger's Cat: https://en.wikipedia.org/wiki/Schr%C3%B6dinger's_cat
    Open-source: https://en.wikipedia.org/wiki/Open-source_model
    Closure: https://en.wikipedia.org/wiki/Closure_(computer_programming)
    Retrocomputing: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md
    Z80 machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z80
    Amiga 500: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#amiga-500
    E-UAE: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#amiga-500
    AmigaDOS 1.3: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#amiga-500
    Apple II: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#apple-ii
    Applesoft BASIC: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#apple-ii
    QEMU: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    DOSBox: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    v86: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    Z-Machine: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z-machine
    Z-Machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z-machine
    Zplet: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z-machine
    IBM PC compatible: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    x86 machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    MS-DOS: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    MS-DOS Batchfile: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    FreeDOS: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    Commodore VIC-20: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-vic-20
    6502 machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#6502
    Commodore 64: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-64
    Commodore BASIC 2.0: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-64
    JaC64: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-64
    native code: https://en.wikipedia.org/wiki/Machine_code

installation:
  data_dirs:
  - data/installation
  template_dirs:
  - templates
  output_dir: installation
  overlay_files: []
  feed_dir: feeds
  dist_map: dist_map.json
  checkout_dir: checkout
  projection_dir: modules
  link_priority:
    Z80 machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z80
    Amiga 500: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#amiga-500
    E-UAE: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#amiga-500
    AmigaDOS 1.3: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#amiga-500
    Apple II: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#apple-ii
    Applesoft BASIC: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#apple-ii
    QEMU: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    DOSBox: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    v86: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    Z-Machine: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z-machine
    Z-Machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z-machine
    Zplet: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#z-machine
    IBM PC compatible: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    x86 machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    MS-DOS: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    MS-DOS Batchfile: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    FreeDOS: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#ms-dos
    Commodore VIC-20: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-vic-20
    6502 machine code: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#6502
    Commodore 64: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-64
    Commodore BASIC 2.0: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-64
    JaC64: https://github.com/catseye/Chrysoberyl/blob/master/article/Retrocomputing.md#commodore-64
    native code: https://en.wikipedia.org/wiki/Machine_code
