# encoding: UTF-8

"""Functions for loading Chrysoberyl data from a set of Yaml files.

"""

import codecs
import os

import yaml
try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader
try:
    from yaml import CDumper as Dumper
except ImportError:
    from yaml import Dumper


def load_chrysoberyl_dirs(dirnames):
    """Given a list of directory names, load Chrysoberyl data from all
    Yaml files in those directories.

    """
    data = {}

    count = 0
    for dirname in dirnames:
        for root, subdirnames, filenames in os.walk(dirname):
            for filename in filenames:
                if filename.endswith('.yaml'):
                    count += 1
                    file = open(os.path.join(root, filename))
                    data.update(yaml.load(file, Loader=Loader))
                    file.close()
            del subdirnames[:]  # don't automatically descend

    print "%d files read." % count
    return data


def load_docs(filename):
    file = open(filename)
    docs = yaml.load(file, Loader=Loader)
    file.close()
    return docs


def save_docs(filename, docdict):
    with codecs.open(filename, 'w', 'utf-8') as file:
        file.write('# encoding: UTF-8\n')
        file.write('# AUTOMATICALLY GENERATED BY chrysoberyl.py\n')
        file.write(yaml.dump(docdict, Dumper=Dumper, default_flow_style=False))
