#!/usr/bin/env python
# encoding: UTF-8

import json
#from optparse import OptionParser
import os
import re
import sys

#sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])), '..', 'src'))

#from chrysoberyl import commands


def rewrite_json():

    with open('distribution/distributions.json', 'r') as f:
        distributions = json.loads(f.read())

    for key, node in distributions.iteritems():
        if 'type' in node:
            del node['type']

    with open('distribution/distributions.json', 'w') as f:
        f.write(json.dumps(distributions, indent=4, sort_keys=True))


if __name__ == '__main__':
    rewrite_json()
